import type { Question, Template } from "./data";

type AnswerState = { answer: "yes" | "no" | "n/a" | ""; comments: string; photos: string[] };

export function buildEmailReport({
  facility,
  address,
  inspector,
  date,
  generalComments,
  questions,
  answers,
  template,
}: {
  facility: string;
  address: string;
  inspector: string;
  date: string;
  generalComments: string;
  questions: Question[];
  answers: Record<number, AnswerState>;
  template: Template;
}): string {
  const formattedDate = new Date(date + "T12:00:00").toLocaleDateString("en-US", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });

  const yesCount = questions.filter(q => answers[q.id]?.answer === "yes").length;
  const noCount  = questions.filter(q => answers[q.id]?.answer === "no").length;
  const naCount  = questions.filter(q => answers[q.id]?.answer === "n/a").length;

  const sections = [...new Set(questions.map(q => q.section))];

  let body = "";
  body += `${template.name.toUpperCase()}\n`;
  body += `${"=".repeat(60)}\n\n`;
  body += `Facility:        ${facility}\n`;
  if (address) body += `Address:         ${address}\n`;
  body += `Inspector:       ${inspector}\n`;
  body += `Inspection Date: ${formattedDate}\n`;
  body += `Report Type:     ${template.type === "spcc" ? "SPCC — 40 CFR Part 112" : "Stormwater — MSGP/SWPPP"}\n`;
  body += `\n`;

  body += `SUMMARY\n`;
  body += `${"─".repeat(40)}\n`;
  body += `  YES:   ${yesCount}\n`;
  body += `  NO:    ${noCount}${noCount > 0 ? "  ← ACTION REQUIRED" : ""}\n`;
  body += `  N/A:   ${naCount}\n`;
  body += `  TOTAL: ${questions.length}\n`;
  body += `\n`;

  if (noCount > 0) {
    body += `⚠️  ACTION REQUIRED: ${noCount} item${noCount > 1 ? "s were" : " was"} answered NO. Review findings below and take corrective action.\n\n`;
  } else {
    body += `✓  All items satisfactory — no deficiencies noted.\n\n`;
  }

  if (generalComments.trim()) {
    body += `GENERAL COMMENTS\n`;
    body += `${"─".repeat(40)}\n`;
    body += `${generalComments.trim()}\n\n`;
  }

  body += `INSPECTION DETAIL\n`;
  body += `${"=".repeat(60)}\n\n`;

  sections.forEach(section => {
    const sectionQs = questions.filter(q => q.section === section);
    body += `[ ${section.toUpperCase()} ]\n`;
    body += `${"─".repeat(50)}\n`;

    sectionQs.forEach((q, idx) => {
      const a = answers[q.id] || { answer: "", comments: "", photos: [] };
      const ansLabel = a.answer === "yes" ? "YES" : a.answer === "no" ? "NO " : a.answer === "n/a" ? "N/A" : "---";
      const flag = a.answer === "no" ? " ← ACTION REQUIRED" : "";
      body += `${String(idx + 1).padStart(2, " ")}. [${ansLabel}]${flag}\n`;
      body += `    ${q.questionText}\n`;
      if (a.comments.trim()) {
        body += `    Comments: ${a.comments.trim()}\n`;
      }
      if (a.photos.length > 0) {
        body += `    Photos: ${a.photos.length} photo${a.photos.length > 1 ? "s" : ""} attached to inspection record\n`;
      }
      body += `\n`;
    });
  });

  body += `${"=".repeat(60)}\n`;
  body += `Report generated by Midwest Training and Consulting Services\n`;
  body += `Powered by Midwest Training and Consulting Services (MTCS)\n`;
  body += `midwest-training.com\n`;

  return body;
}
